version: 0.2

phases:
  build:
    commands:
    - echo "Deploying Static Website"

  post_build:
    commands:
    - echo "Uploading frontend files to S3..."
    - aws s3 sync . s3://21082026-azdemoapp-s3-bucket --delete
    - echo "S3 upload completed"
    - aws cloudfront create-invalidation --distribution-id E30C6KUB8EREPP --paths "/*" --debug
