version: 0.2

phases:
  build:
    commands:
    - echo "Deploying Static Website"

  post_build:
    commands:
    - echo "Uploading frontend files to S3..."
    - aws s3 sync . s3://20082026-azdemo-s3bucket --delete
    - echo "S3 upload completed"
    - aws cloudfront create-invalidation --distribution-id EVK9QOLXOFJJ9 --paths "/*" --debug
